USE [SUPER_NOVA]
GO

/****** Object:  Table [dbo].[TB_SN_USUARIOS]    Script Date: 21/12/2020 21:54:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_SN_USUARIOS](
	[ID_USUARIO] [int] IDENTITY(1,1) NOT NULL,
	[DS_NOME_USUARIO] [varchar](250) NOT NULL,
	[DS_LOGIN_USUARIO] [varchar](250) NOT NULL,
	[DS_PASSWORD_USUARIO] [varchar](250) NOT NULL,
	[FL_STATUS_USUARIO] [bit] NOT NULL,
	[DS_IMG_USUARIO] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

USE [SUPER_NOVA]
GO

/****** Object:  Table [dbo].[TB_SN_TIPO_FACAS]    Script Date: 21/12/2020 21:54:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_SN_TIPO_FACAS](
	[ID_TIPO_FACAS] [int] IDENTITY(1,1) NOT NULL,
	[DS_TIPO_FACAS] [varchar](250) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_TIPO_FACAS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [SUPER_NOVA]
GO

/****** Object:  Table [dbo].[TB_SN_MAQUINA_FACAS]    Script Date: 21/12/2020 21:54:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_SN_MAQUINA_FACAS](
	[ID_MAQUINA_FACA] [int] IDENTITY(1,1) NOT NULL,
	[DS_MAQUINA_FACA] [varchar](250) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_MAQUINA_FACA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO



USE [SUPER_NOVA]
GO

/****** Object:  Table [dbo].[TB_SN_FACAS]    Script Date: 21/12/2020 21:54:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_SN_FACAS](
	[ID_FACA] [int] IDENTITY(1,1) NOT NULL,
	[ID_MAQUINA_FACA] [int] NOT NULL,
	[ID_TIPO_FACAS] [int] NOT NULL,
	[VL_LARGURA_FACA] [numeric](10, 2) NOT NULL,
	[VL_ALTURA_FACA] [numeric](10, 2) NOT NULL,
	[NR_FACA] [int] NOT NULL,
	[NR_COLUNAS_FACA] [int] NOT NULL,
	[NR_LINHAS_FACA] [int] NOT NULL,
	[DS_CAIXA_FACA] [varchar](300) NOT NULL,
	[DS_CLIENTE_FACA] [varchar](150) NULL,
	[DS_OBSERVACAO] [varchar](150) NULL,
	[DS_URL_IMG] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_FACA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[TB_SN_FACAS]  WITH CHECK ADD  CONSTRAINT [FK_MAQUINA_FACA] FOREIGN KEY([ID_MAQUINA_FACA])
REFERENCES [dbo].[TB_SN_MAQUINA_FACAS] ([ID_MAQUINA_FACA])
GO

ALTER TABLE [dbo].[TB_SN_FACAS] CHECK CONSTRAINT [FK_MAQUINA_FACA]
GO

ALTER TABLE [dbo].[TB_SN_FACAS]  WITH CHECK ADD  CONSTRAINT [FK_TIPO_FACA] FOREIGN KEY([ID_TIPO_FACAS])
REFERENCES [dbo].[TB_SN_TIPO_FACAS] ([ID_TIPO_FACAS])
GO

ALTER TABLE [dbo].[TB_SN_FACAS] CHECK CONSTRAINT [FK_TIPO_FACA]
GO




