CREATE TABLE TB_SN_CLASSIFICACAO_PRODUTO(
	 ID_CLASSIFICACAO_PRODUTO INT PRIMARY KEY IDENTITY(1,1) NOT NULL
	,DS_CLASSIFICACAO_PRODUTO NVARCHAR(200) NOT NULL
);

CREATE TABLE TB_SN_PRODUTO(
	 ID_PRODUTO INT PRIMARY KEY IDENTITY(1,1) NOT NULL
	,DS_PRODUTO NVARCHAR(200) NOT NULL
	,ID_CLASSIFICACAO_PRODUTO INT NOT NULL
	,CONSTRAINT FK_CLASSIFICACAO FOREIGN KEY (ID_CLASSIFICACAO_PRODUTO) 
	 REFERENCES TB_SN_CLASSIFICACAO_PRODUTO (ID_CLASSIFICACAO_PRODUTO)
);


CREATE TABLE TB_SN_USUARIO(
	 ID_USUARIO INT PRIMARY KEY IDENTITY(1,1) NOT NULL
	,DS_NOME NVARCHAR(200) NOT NULL
	,LOGIN_USUARIO NVARCHAR(200) NOT NULL
	,SENHA_USUARIO NVARCHAR(200) NOT NULL
	,FL_ATIVO BIT NOT NULL
);


CREATE TABLE TB_SN_ENTREGA(
	 ID_ENTREGA INT PRIMARY KEY IDENTITY(1,1) NOT NULL
	,DS_ENTREGA NVARCHAR(200) NOT NULL
	,OBS_ENTREGA NVARCHAR(500) NULL
);

CREATE TABLE TB_SN_TIPO_PEDIDO(
	 ID_TIPO_PEDIDO INT PRIMARY KEY IDENTITY(1,1) NOT NULL
	,DS_TIPO_PEDIDO NVARCHAR(200) NOT NULL
	,NR_SLA_DIAS INT NULL
);

CREATE TABLE TB_SN_ETAPAS_TIPO_PEDIDO(
	 ID_ETAPA_TIPO_PEDIDO INT PRIMARY KEY IDENTITY(1,1) NOT NULL
	,DS_ETAPA_TIPO_PEDIDO NVARCHAR(200) NOT NULL
	,ID_TIPO_PEDIDO INT NOT NULL
	,NR_SLA_DIAS INT NULL
	,NR_ORDEM INT NULL
	,FL_INICIAL BIT NULL
	,FL_FINAL BIT NULL
	,CONSTRAINT FK_TIPO_CORTE FOREIGN KEY (ID_ETAPA_TIPO_PEDIDO) 
	 REFERENCES TB_SN_TIPO_PEDIDO (ID_TIPO_PEDIDO)
);
CREATE TABLE TB_SN_ORDEM_SERVICO(
	ID_ORDEM_SERVICO INT PRIMARY KEY IDENTITY(1,1) NOT NULL
	,DT_INICIO DATETIME NOT NULL
	,DT_FIM DATETIME NULL
	,DT_PED_ANTERIOR DATETIME NULL
	,ID_ATENDENTE INT NOT NULL
	,ID_ENTREGA INT NOT NULL
	,CONSTRAINT FK_ENTREGA FOREIGN KEY (ID_ENTREGA) 
	 REFERENCES TB_SN_ENTREGA (ID_ENTREGA)
);
CREATE TABLE TB_SN_PEDIDO(
	 ID_PEDIDO INT PRIMARY KEY IDENTITY(1,1) NOT NULL
	,DS_PEDIDO NVARCHAR(200) NOT NULL
	,DS_ARQUIVO NVARCHAR(150) NULL
	,ID_ORDEM_SERVICO INT NOT NULL
	,ID_PRODUTO INT NOT NULL
	,ID_TIPO_PEDIDO INT NOT NULL
	,ID_ETAPA_TIPO_PEDIDO INT NOT NULL
	,ID_ATENDENTE INT NOT NULL

	,FL_FICHA_TECNICA BIT NULL
	,FL_VARIACAO_MATERIAL BIT NULL
	,FL_TOMBO BIT NULL
	,FL_AMOSTRA BIT NULL

	,CONSTRAINT FK_ORDEM_SERVICO FOREIGN KEY (ID_ORDEM_SERVICO) 
	 REFERENCES TB_SN_ORDEM_SERVICO (ID_ORDEM_SERVICO)

	,CONSTRAINT FK_TIPO_PEDIDO FOREIGN KEY (ID_TIPO_PEDIDO) 
	 REFERENCES TB_SN_TIPO_PEDIDO (ID_TIPO_PEDIDO)

	,CONSTRAINT FK_ETAPAS_TIPO_PEDIDO FOREIGN KEY (ID_ETAPA_TIPO_PEDIDO) 
	 REFERENCES TB_SN_ETAPAS_TIPO_PEDIDO (ID_ETAPA_TIPO_PEDIDO)

	,CONSTRAINT FK_ATENDENTE FOREIGN KEY (ID_ATENDENTE) 
	 REFERENCES TB_SN_USUARIO (ID_USUARIO)
	
	,CONSTRAINT FK_PRODUTO FOREIGN KEY (ID_PRODUTO) 
	 REFERENCES TB_SN_PRODUTO (ID_PRODUTO)
);

CREATE TABLE TB_SN_PEDIDO_HISTORICO(
	 ID_PEDIDO_HISTORICO INT PRIMARY KEY IDENTITY(1,1) NOT NULL
	,DT_CADASTRO DATETIME NOT NULL
	,ID_PEDIDO INT NOT NULL
	,ID_USUARIO INT NOT NULL
	,ID_TIPO_PEDIDO INT NOT NULL
	,ID_ETAPA_TIPO_PEDIDO INT NOT NULL
	,FL_SISTEMA_USUARIO BIT NOT NULL
	,CONSTRAINT FK_PEDIDO FOREIGN KEY (ID_PEDIDO) 
	 REFERENCES TB_SN_PEDIDO (ID_PEDIDO)
	,CONSTRAINT FK_ATENDENTE FOREIGN KEY (ID_USUARIO) 
	 REFERENCES TB_SN_USUARIO (ID_USUARIO)
	,CONSTRAINT FK_TIPO_PEDIDO FOREIGN KEY (ID_TIPO_PEDIDO) 
	 REFERENCES TB_SN_TIPO_PEDIDO (ID_TIPO_PEDIDO)
	,CONSTRAINT FK_ETAPAS_TIPO_PEDIDO FOREIGN KEY (ID_ETAPA_TIPO_PEDIDO) 
	 REFERENCES TB_SN_ETAPAS_TIPO_PEDIDO (ID_ETAPA_TIPO_PEDIDO)
);