//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperNovaDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SN_TIPO_FACAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_SN_TIPO_FACAS()
        {
            this.TB_SN_FACAS = new HashSet<TB_SN_FACAS>();
        }
    
        public int ID_TIPO_FACAS { get; set; }
        public string DS_TIPO_FACAS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_SN_FACAS> TB_SN_FACAS { get; set; }
    }
}
