//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperNovaDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SN_FACAS
    {
        public int ID_FACA { get; set; }
        public int ID_MAQUINA_FACA { get; set; }
        public int ID_TIPO_FACAS { get; set; }
        public decimal VL_LARGURA_FACA { get; set; }
        public decimal VL_ALTURA_FACA { get; set; }
        public int NR_FACA { get; set; }
        public int NR_COLUNAS_FACA { get; set; }
        public int NR_LINHAS_FACA { get; set; }
        public string DS_CAIXA_FACA { get; set; }
        public string DS_CLIENTE_FACA { get; set; }
        public string DS_OBSERVACAO { get; set; }
        public string DS_URL_IMG { get; set; }
    
        public virtual TB_SN_MAQUINA_FACAS TB_SN_MAQUINA_FACAS { get; set; }
        public virtual TB_SN_TIPO_FACAS TB_SN_TIPO_FACAS { get; set; }
    }
}
