//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperNovaDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SN_USUARIOS
    {
        public int ID_USUARIO { get; set; }
        public string DS_NOME_USUARIO { get; set; }
        public string DS_LOGIN_USUARIO { get; set; }
        public string DS_PASSWORD_USUARIO { get; set; }
        public bool FL_STATUS_USUARIO { get; set; }
        public string DS_IMG_USUARIO { get; set; }
    }
}
