CREATE TABLE TB_SN_MAQUINA_FACAS(
	 ID_MAQUINA_FACA INT IDENTITY(1,1) NOT NULL PRIMARY KEY
	 ,DS_MAQUINA_FACA VARCHAR(250) NOT NULL
);
GO
CREATE TABLE TB_SN_TIPO_FACAS(
	  ID_TIPO_FACAS INT IDENTITY(1,1) NOT NULL PRIMARY KEY
	 ,DS_TIPO_FACAS VARCHAR(250) NOT NULL
);
GO
CREATE TABLE TB_SN_FACAS(
	 ID_FACA INT IDENTITY(1,1) NOT NULL PRIMARY KEY
	
	,ID_MAQUINA_FACA INT NOT NULL
	,ID_TIPO_FACAS INT NOT NULL
	,VL_LARGURA_FACA NUMERIC(10,2) NOT NULL
	,VL_ALTURA_FACA NUMERIC(10,2) NOT NULL

	,NR_FACA INT NOT NULL
	,NR_COLUNAS_FACA INT NOT NULL
	,NR_LINHAS_FACA INT NOT NULL
	
	,DS_CAIXA_FACA VARCHAR(300) NOT NULL
	,DS_CLIENTE_FACA VARCHAR(150) NULL
	,DS_OBSERVACAO VARCHAR(150) NULL

	,CONSTRAINT FK_MAQUINA_FACA FOREIGN KEY (ID_MAQUINA_FACA) 
	  REFERENCES TB_SN_MAQUINA_FACAS (ID_MAQUINA_FACA)
	,CONSTRAINT FK_TIPO_FACA FOREIGN KEY (ID_TIPO_FACAS) 
	  REFERENCES TB_SN_TIPO_FACAS (ID_TIPO_FACAS)
);
GO

